# Generated by Django 6.0.6 on 2026-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome class, e.g. fa-solid fa-wrench', max_length=100),
        ),
    ]
