# Generated by Django 6.0.6 on 2026-07-03 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_alter_service_options_alter_service_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[('0-1', '0-1 Year'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5+', '5+ Years')], max_length=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='workers/')),
                ('verified', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(to='services.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
